version: 2.1

commands:
  cmd_deploy:
    description: "Deploy k8s configs to GKE"
    parameters:
      priorityClass:
        type: string
        default: "priority-class.yaml"
      tillerRBAC:
        type: string
        default: "tiller/rbac-config.yaml"
      tillerPatchDeployment:
        type: string
        default: "tiller/patch-deployment.yaml"
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ./gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            rm ./gcloud-service-key.json

      - run:
          name: Setup PriorityClass
          command: |
            kubectl apply -f << parameters.priorityClass >>

            ################
            ## validation ##
            ################
            kubectl get priorityclasses.scheduling.k8s.io

      - run:
          name: Install Helm and Tiller
          command: |
            # install helm
            curl https://raw.githubusercontent.com/helm/helm/v2.14.3/scripts/get | bash
            kubectl apply -f << parameters.tillerRBAC >>

            # install tiller
            helm init --service-account tiller --history-max 200

            ################
            ## validation ##
            ################

            # should see tiller running
            kubectl get pods --namespace kube-system

            # should show you both the client and server version
            helm version

      # Not Working...
      #
      # - run:
      #     name: Patch Tiller
      #     command: |
      #       kubectl patch deployment tiller-deploy --patch "$(cat << parameters.tillerPatchDeployment >>)" --namespace kube-system

      #       ################
      #       ## validation ##
      #       ################
      #       kubectl get deployment tiller-deploy --output yaml --namespace kube-system

jobs:
  deploy_to_staging:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/my-working-directory
    environment:
      - GOOGLE_PROJECT_ID: "cubee-247317"
      - GOOGLE_COMPUTE_ZONE: "asia-east1-a"
      - GOOGLE_CLUSTER_NAME: "cubee-stg"
    steps:
      - cmd_deploy:
          priorityClass: "priority-class.yaml"
          tillerRBAC: "tiller/rbac-config.yaml"
          tillerPatchDeployment: "tiller/patch-deployment.yaml"
  # deploy_to_production:
  #   docker:
  #     - image: google/cloud-sdk
  #   working_directory: ~/my-working-directory
  #   environment:
  #     - GOOGLE_PROJECT_ID: "cubee-247317"
  #     - GOOGLE_COMPUTE_ZONE: "us-west1-a"
  #     - GOOGLE_CLUSTER_NAME: "cubee-prod"
  #   steps:
  #     - cmd_deploy:
  #         tillerRBACFileName: "tiller/rbac-config.yaml"

workflows:
  version: 2
  deploy_k8s_config:
    jobs:
      - deploy_to_staging:
          filters:
            branches:
              only: master
            tags:
              only: /release-.*/
      # - deploy_to_production:
      #     requires:
      #       - deploy_to_staging
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /release-.*/
