ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.cubee.cc
  tls:
    - secretName: cubee-cc-tls
      hosts:
        - cubee.cc
        - "*.cubee.cc"

persistence:
  enabled: true
  storageClassName: standard
  size: 5Gi
